---
engines:
  csslint:
    enabled: true
    exclude_fingerprints:
    - beed1e710ac074c6ad8e516ce0d18ec6
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.html"
  - "**.js"
  - "**.htaccess"
  - "**.txt"
  - "**.xml"
exclude_paths:
  - "assets/"
  - "process/js/custom.js"
