# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pollutants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('concen', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Area')),
            ],
        ),
    ]
